# docker compose file
version: '3.7'

services:

  api:
    image: api
    build:
      context: ./api
      dockerfile: ./Dockerfile
      args:
        - API_PORT=${API_PORT}
    # # left port is the port to the world(aka the host). right port is the port the container exposed
    # ports:
    #   - 8000:${API_PORT}
  
  nginx:
    image: nginx
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    links:
      - "api:${API_HOSTNAME}"
    depends_on:
      - api
    environment:
      - API_PORT
      - API_HOSTNAME
    volumes:
      - ./nginx/debug:/app/output
